name: Build and Deploy

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy React app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p app
            cd app
            git clone git@github.com:gabrielnatangw/docker-image.git
            echo 'Deploy on digital ocean'
            echo '--------------------------------'
            pwd
            ls
            echo '--------------------------------'
            cd docker-image
            pwd
            echo '--------------------------------'
            docker build -t docker/image .
            docker run -p 80:80 --name docker-build docker/image
