name: image

on:
  push:
    branches: [main]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/smart/image-docker:latest
          docker push ghcr.io/smart/image-docker:latest
